fn main() {
    println!("Hello, world!");

    // unsafe { extern_kernels::test_kernel() }
}
pub mod gemm;
pub mod kernel;

/// Generated by the build.rs file.
pub mod extern_kernels {
    include!(concat!(env!("OUT_DIR"), "/extern_kernels.rs"));
}
